#
# Jz4750 Platform Support
#
snd-soc-jz4750-objs := jz4750-pcm.o
snd-soc-jz4750-i2s-objs := jz4750-i2s.o

obj-$(CONFIG_SND_JZ4750_SOC) += snd-soc-jz4750.o
obj-$(CONFIG_SND_JZ4750_SOC_I2S) += snd-soc-jz4750-i2s.o

# Jz4750 Machine Support
snd-soc-a380-objs := a380.o
snd-soc-rzx50-objs := rzx50.o

obj-$(CONFIG_SND_JZ4750_SOC_A380) += snd-soc-a380.o
obj-$(CONFIG_SND_JZ4750_SOC_RZX50) += snd-soc-rzx50.o
