#
# Makefile for jzchar
#
obj-$(CONFIG_JZCHAR)		+= jzchars.o
obj-$(CONFIG_JZ_SADC)		+= jz_sadc.o
obj-$(CONFIG_JZ_UDC_HOTPLUG)	+= udc_hotplug.o
obj-$(CONFIG_JZ_GSENSOR)	+= gsensor.o
obj-$(CONFIG_JZ_RADIO_RDA5807P)	+= radio-rda5807p.o
obj-$(CONFIG_JZ_A380_ELAN)	+= elan.o
obj-$(CONFIG_JZ_POWEROFF)	+= poweroff.o
obj-$(CONFIG_JZ_TCSM)	+= tcsm.o
